apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  namespace: tls-gw-api
spec:
  type: ClusterIP
  selector:
    app: echoserver-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-depl
  namespace: tls-gw-api
  labels:
    app: echoserver-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-app
      version: v1
  template:
    metadata:
      labels:
        app: echoserver-app
        version: v1
    spec:
      containers:
        - name: echoserver-app
          image: imeshai/echoserver
          ports:
            - containerPort: 80
