apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/dataplane-mode: ambient
  name: ns2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-service-account-ns2
  namespace: ns2
  labels:
    account: echoserver-app-ns2
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service-ns2
  namespace: ns2
spec:
  type: ClusterIP
  selector:
    app: echoserver-app-ns2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-depl-ns2-v1
  namespace: ns2
  labels:
    app: echoserver-app-ns2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-app-ns2
      version: v1
  template:
    metadata:
      labels:
        app: echoserver-app-ns2
        version: v1
    spec:
      serviceAccountName: echo-service-account-ns2
      containers:
        - name: echoserver-app-ns2
          image: imeshai/echoserver
          ports:
            - containerPort: 80
      nodeSelector:
        name: node2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-depl-ns2-v2
  namespace: ns2
  labels:
    app: echoserver-app-ns2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-app-ns2
      version: v2
  template:
    metadata:
      labels:
        app: echoserver-app-ns2
        version: v2
    spec:
      serviceAccountName: echo-service-account-ns2
      containers:
        - name: echoserver-app-ns2
          image: imeshai/echoserver
          ports:
            - containerPort: 80
      nodeSelector:
        name: node2
